### PR TITLE
Fix link to build result

### PR DESCRIPTION
**Pull request by alecharp**
Replacing all "/" by " :: " as it was done in 2.2.4

### CODE REVIEW

**Comment by eyalbe4** [comment]
Hi @alecharp ,
Is this fix still relevant with the latest release of the plugin? If so, can please describe problematic scenario and the issue? Thanks!

**Comment by alecharp** [comment]
I haven't tested it since February, when I did this pull-request.

**Comment by eyalbe4** [comment]
Hi @alecharp, please let us know if the fix is still required with the latest release. If it is not needed anymore, we will close this request. Thanks.

**Comment by DPD-30** [comment]
Yes this is still an issue plugin version 2.7.2.  With a multi branch pipeline the name include " :: " and also '%2F' if subfolders exist in the name.  The build gets created in artifactory but is not is not retrieveable in artifactory.

**Comment by eyalbe4** [comment]
@alecharp, I guess that this PR can be closed, because https://github.com/JFrogDev/jenkins-artifactory-plugin/pull/35 includes this PR's fix.

**Comment by alecharp** [comment]
it seems so yes.

**Pull request closed without merging**
