### PR TITLE
JENKINS-41059 update docker-java

### PR DESCRIPTION
**Pull request by sebglon**

### CODE REVIEW

**Comment by eyalbe4** [comment]
Thanks for the pull request @sebglon.
Can you please sign [JFrog CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we're able to merge your changes?
Also, did you test this change? Did it resolve the issue?

**Comment by sebglon** [comment]
I have sign Jfrog CLA now;
this is tested and solved JENKINS-41059 but not JENKINS-40037

On continue to work on debug and analyse JENKINS-40037

**Comment by eyalbe4** [comment]
Thank you for this @sebglon.
If you find the root cause of JENKINS-40037 and have a fix that resolves it, we'd be happy to accept it.

**Comment by sebglon** [comment]
On what version of the plugin this PR is embeded?

**Pull request merged**
