### PR TITLE
Only git push after build is successful (avoid intermediate pushes) - fixes HAP-809

### PR DESCRIPTION
**Pull request by KostaCitrix**
Hi!

I created [HAP-809](https://www.jfrog.com/jira/browse/HAP-809) and this PR fixes it.

See that issue for more details, but basically this changes the ordering of the release build like this:
- After setting the release version, commit & tag immediately, so that the release build has the right commit and the working directory is clean
- Only push at the very end (both branches if there's a release branch), so that we never have to delete a remote branch. We only do one single push in the non-release-branch case which can avoid issues with git repo post-commit-hooks that can cause two release builds on our systems. (One being triggered by the plugin and one by the post-commit hook of the release version on the master branch)

This is currently untested. What kind of unit tests make sense here? I will test this on our jenkins dev instance and get back to you. In the meantime, I would be very happy if you could comment on the code itself and whether you're willing to merge it in general.

Thanks in advance!

Cheers,
Kosta

### CODE REVIEW

**Comment by eyalbe4** [comment]
Thank you for this @KostaCitrix. The idea is indeed interesting, but we see the following downside if we adopt it:
In case you decide to stop the build while it is running, you have to delete your local git cache, so that you can run the build again. Many users have their local maven repo in the workspace, and deleting the workspace will have all dependencies resolved again, making the build a lot longer.
What do you think about this implication? If Jenkins had a convenient way to wipe out the git cache only, and not the entire workspace, then that would probably resolve this issue.

**Comment by KostaCitrix** [comment]
Hi!

Thanks for taking a look at my PR! I'm not sure how my PR affects the behaviour you describe. The local git should behave exactly the same.

The only thing that changed in case of unsuccessful build (we're talking about the `else` in `buildCompleted()`, right?) is that we don't have to delete the remote git branch because we did not push it yet.

Please let me know how I can improve the "local git cache" behaviour and I'd be happy to implement it.

Cheers,
Kosta

**Comment by eyalbe4** [comment]
@KostaCitrix, let me try and explain my point about cleaning up the git local cache:
With the current Release Staging process implementation, in case you stop the release while maven is running, you can run the release build again without wiping out the local git cache.
In the new suggested implementation, because you commit locally before the maven build, after stopping the build, you must revert the local commit before running the build again. Keep in mind that for many projects, the maven build can take a very long time to run.

**Comment by KostaCitrix** [comment]
That is a very good point! Thank you for raising it and thanks for the detailed explanation! (I didn't get it before)

I would propose the following:
* When checking out the branch, I remember the exact commit of the checkoutBranch ([using `revParse()`](https://github.com/jenkinsci/git-client-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java#L622)?)
* In `revertWorkingCopy()`, git reset --hard the branch to that commit ([using `checkoutBranch`](https://github.com/jenkinsci/git-client-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java#L265))

This should take care of having the Workspace back in the same state as when the build started.

Sounds good?

Cheers,
Kosta

**Comment by eyalbe4** [comment]
@KostaCitrix, sounds good, but we'll need to make sure the *revertWorkingCopy()* method is invoked when the build is manually interrupted.

**Comment by KostaCitrix** [comment]
This would be done in `buildCompleted()`, right? (as it is now with `safeRevertWorkingCopy()`), correct?

**Comment by eyalbe4** [comment]
I'm almost sure about this @KostaCitrix, but you'll probably be able to verify that while debugging the code.
Please let us know if you manage to revert the local commits when the build fails and also when the build is interrupted manually from the UI. 
If all goes well, then we can adopt the new flow.

**Comment by KostaCitrix** [comment]
Thank you @eyalbe4! 

I implemented the improvement we discussed, but it's completely untested yet. I will be travelling the next four days and test on Monday. You'll hear back from me then. (Until then, feel free to comment on my code of course)

Should I try to create Unit tests for this? I would use mocks to make sure the correct calls to GitManager are made for each flow. This would test the possible combinations, such as: 
* whether to create a tag
* whether to create a release branch
* whether versions are changed at all

**Comment by eyalbe4** [comment]
Thanks @KostaCitrix. 
We'll be waiting for your tests confirmation, including the failure scenarios we discussed.
Sure - unit tests would be nice.

**Comment by KostaCitrix** [comment]
__tl/dr__: Fixed a bug, please merge 👍 ! Need advice on unit tests :)

I tested this thoroughly today and found two bugs if no local modification occurred (thus, no version change and no commit)
* The code still pushed the checkout branch (even though there was nothing to push)
* The code never parsed the git revision thus creating a NPE when reverting (even though there was nothing to revert)

Both are fixed in 9d76e74. I think this should be mergeable.

Cancelling the build had the same effect as failing tests: The else branch in `buildCompleted()` got triggered (as desired).

I tested the following scenarios, for "build success", "build unstable (test failures)" and "build cancelled". In the non-success cases, I made sure all local modifications are reverted hard. 

* Release build without version number changes, no tag, no release branch (which basically means the plugin doesn't do anything but still it should behave correctly)
* Release build with version number change; no tag; no release branch
* Release build with version number change; tagged; no release branch
* Release build with version number change; tagged; release branch

Side note: When running a release build without version number changes but with creating a tag or a branch, the tag or branch is never created. This is because `MavenReleaseWrapper.setUp()` never calls `afterReleaseVersionChange()`. This seems to be on purpose. In any case, this is the pre-existing behaviour and should be fixed in a separate issue/PR.

In the non-success cases, no commit/branch/tag is ever pushed, which is a very nice property that didn't exist before. In the success cases, the commits are only pushed at the very end and using only one single push per branch which fixes the race conditions when using post-commit hooks. All in all, I like the new behaviour very much 👍 

I have some trouble writing good Unit Tests. The only way I found was to hide `hudson.model.AbstractBuild` behind a thin Interface so that I can mock that instead of AbstractBuild. Here's the changes to production code. The unit tests are not ready yet but I will continue if that approach is acceptable: https://github.com/KostaCitrix/jenkins-artifactory-plugin/compare/master...KostaCitrix:GitCoordinator-tests?expand=1

Please let me know if that approach to makting GitCoordinator unit-testable through mocks is worth pursuing!

Thank you in advance for your time & consideration!

Cheers,
Kosta

**Comment by KostaCitrix** [comment]
I finished the Unit Tests. I'm not 100% satisfied with them because they are using Mocks too much. Please let me know what you think. They currently live in the [GitCoordinator-Test branch](https://github.com/KostaCitrix/jenkins-artifactory-plugin/compare/master...KostaCitrix:GitCoordinator-tests?expand=1).

[Example of a "Success" test case](https://github.com/KostaCitrix/jenkins-artifactory-plugin/compare/master...KostaCitrix:GitCoordinator-tests?expand=1#diff-fc9df13c3637fb4c429bdcbfe8a42c97R146)

[Example of a "Aborted" test case](https://github.com/KostaCitrix/jenkins-artifactory-plugin/compare/master...KostaCitrix:GitCoordinator-tests?expand=1#diff-fc9df13c3637fb4c429bdcbfe8a42c97R224)

I think these unit tests make some sense, especially making sure that in the failure scenarios nothing was ever pushed and the working copy is reverted correctly.

**Comment by KostaCitrix** [comment]
Is there anything I can do to help move this forward?

**Comment by eyalbe4** [comment]
Hi @KostaCitrix,
Thanks again for the effort and contribution. We will review this soon.

**Comment by KostaCitrix** [comment]
Hi!

Is there anything I can do to facilitate the code review?

Thanks in advance!

Cheers,
Kosta

**Comment by KostaCitrix** [comment]
Hi!

I'd propose:
* Merge this PR & test it manually
* Discard the "Unit testing" branch (doesn't fit the existing code)

Sounds good?

Cheers,
Kosta

**Comment by KostaCitrix** [comment]
Is there anything I can do to move this forward?
(This is your weekly reminder ;) )

**Comment by eyalbe4** [comment]
Thanks for the great contribution @KostaCitrix and my apologies for the delay.
Can you please sign [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge your code?

**Comment by KostaCitrix** [comment]
Thank you for your response! 

I have to pass this by our legal department but I'm confident I can sign this shortly.

Cheers,
Kosta

**Comment by KostaCitrix** [comment]
Unfortunately I am not able to sign this currently due to internal reasons. I will re-open this PR in February 2017 and hope it can be merged then.

I am sorry for the unnecessary effort I put on you!

Kind regards,
Kosta

**Pull request closed without merging**
