### PR TITLE
HAP-373 - For multi-module M2 release builds, don't publish artifacts

### PR DESCRIPTION
**Pull request by StevenGBrown**
When releasing a single Maven module with the M2 Release plugin, the
ArtifactoryRedeployPublisher does not publish any artifacts. This was
implemented under HAP-93.

This change makes multi-module Maven builds act the same way. The
artifactory plugin will act as if there is no ArtifactoryRedeployPublisher
configured when performing a M2 Release, and so will not deploy artifacts.

See also JENKINS-16780, which appears to describe the same bug.

### CODE REVIEW

**Comment by srinath45** [comment]
Hi,
I am using Artifactory plugin 2.16.2 to record buildinfo and jgitflow:release-finish to make a release. jgitflow:release-finish command creates release branch and builds that branch to generate release artifacts. Artifactory is recording execution of jgitflow:release-finish command, but it is not recording the build of release branch, so, I am not able to deploy release artifacts to Artifactory.

**Comment by srinath45** [comment]
Is there any parameter to Initialize Artifactory buildinfo recording

**Comment by eyalbe4** [comment]
@srinath45,
Are you using a pipeline job?
If so, can you please share a sample of the pipeline script, so that we can better understand the flow?

**Comment by eyalbe4** [comment]
@srinath45,
The Jenkins Artifactory Plugin maven API is tied to the **install** maven goal, which is not used in your **rtMaven.run** method. This is probably the reason why artifacts are not deployed to Artifactory by your pipeline script.

**Comment by eyalbe4** [comment]
Correct @srinath45.
The Artifactory Plugin cannot hook with maven's default deployment goal. Please consider using the Release Management approach described [here](https://www.jfrog.com/confluence/display/RTF/Working+With+Pipeline+Jobs+in+Jenkins)
Or, if you'd like to use the maven deploy goal, you can use the [Maven Artifactory Plugin](https://www.jfrog.com/confluence/display/RTF/Maven+Artifactory+Plugin)

**Comment by StevenGBrown** [comment]
I don't know

**Pull request merged**
