### PR TITLE
[HAP-484] Apply same fix for HAP-484 to the other project actions.

### PR DESCRIPTION
**Pull request by christ66**
I did not apply the same fix for [HAP-484](https://www.jfrog.com/jira/browse/HAP-484) to the other project actions.

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by recena** [comment]
:bee:

**Comment by christ66** [comment]
@eyalbe4 It looks like my initial fix for the issue was not complete as I forgot about the other project types (like maven and ivy). This PR should fix it for the other project actions.

**Comment by jglick** [comment]
How do you know where to file PRs for this plugin? https://github.com/jenkinsci/artifactory-plugin/pulls has 13 open, https://github.com/JFrogDev/jenkins-artifactory-plugin/pulls has 3…chaos.

**Comment by eyalbe4** [comment]
PRs for the Jenkins Artifactory Plugins should be filed here (https://github.com/JFrogDev/jenkins-artifactory-plugin).
We will review this one soon. Thanks.

**Comment by jglick** [comment]
> PRs for the Jenkins Artifactory Plugins should be filed [elsewhere than the official repository]

Then can you please disable the pull request feature on the official repository to avoid future confusion?

**Comment by eyalbe4** [comment]
Sure. Will do.

**Comment by recena** [comment]
+1 to disable the PR feature

**Comment by eyalbe4** [comment]
@christ66 ,
Thanks for this contribution. Looks like we implemented the same fix in [HAP-663](https://www.jfrog.com/jira/browse/HAP-663) and released it as part of version 2.4.4 of the plugin, so I think this PR can be closed.

**Comment by christ66** [comment]
@eyalbe4 Awesome! I'll mark as closed. Thanks!

**Pull request closed without merging**
