### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by iNikem**

### CODE REVIEW

**Comment by iNikem** [comment]
@jbaruch any progress on this?

**Comment by eyalbe4** [comment]
Hey @iNikem,
I assume that you're looking for the required Maven repositories needed for dependencies resolution for building the plugin. We will soon add this to the plugin's README.md.

**Comment by iNikem** [comment]
Hi. I am looking for the information needed to contribute to the Artifactory. My first struggle was just to build checked out code. So help here would be extremely nice.

If you have any more requirements or rules governing the contribution, the clear explanation of them would be helpful as well.

**Comment by jbaruch** [comment]
Yes, we spoke with @inikem about adding the needed repositories and such, I never got to do it until now :(
Basically the only repos required are oss.jforg.org `libs-release` and `libs-snapshots`.

**Comment by iNikem** [comment]
As you already have the repository section in your pom.xml, may be it can be updated with the correct urls?

**Comment by eyalbe4** [comment]
@iNikem, the pom file has been updated with all the repositories required for the plugin's dependencies resolution. Thanks for pointing out this issue.

**Comment by jfrog-demo** [comment]
And we probably still need to add some line to the contributing doc about
running with the correct profile.

**Comment by iNikem** [comment]
Just to let you know, it seems to be better now, but fails on test compilation.
[ERROR] /Users/Nikem/Documents/workspace/jenkins-artifactory-plugin/src/test/java/org/jfrog/hudson/ArtifactoryRedeployPublisherITest.java:[36,34] error: cannot access TestRule
[INFO] 1 error

**Comment by eyalbe4** [comment]
@iNikem, Please build the plugin with JDK 6. This should resolve the issue.

**Comment by iNikem** [comment]
Sorry, guys. I searched and found jdk6 for Mac. But next I discovered that my maven is JDK7+ only. So I will just give up. Taking into account, that Jenkins itself claims: "Jenkins requires Java7 or above to function. Java8 is recommended", requiring JDK6 to *build* a plugin is too high entry barrier these days.

**Comment by jbaruch** [comment]
@iNikem we understand your frustration. Will work on it.

**Comment by eyalbe4** [comment]
Absolutely @iNikem and @jbaruch .
We will modify the plugin so that it can be built with JDK 7.

**Comment by eyalbe4** [comment]
@iNikem, @jbaruch,
The plugin code is built with JDK 8 since release 2.5.0. If you think the README or plugin documentation should be extended or improved, feel free to suggest the improvements or submit a pull request.

**Comment by eyalbe4** [comment]
@iNikem, @jbaruch, with your permission I'm closing this issue.

**Pull request closed without merging**
